version: '3'

services:
  nodejs-app:
    build: .
    container_name: todolistapi
    ports:
      - "5010:5010"
    environment:
      PORT: 5010
      DB_URL: "mongodb://root:example@mongodb:27017/"
    depends_on:
      - mongodb
    
    volumes:
      - .:/usr/src/app

  mongodb:
    image: mongo:latest
    hostname: mongodb
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: prototype-db
